buildscript {
    repositories {
        // These repositories are only for Gradle plugins, put any other repositories in the repository block further below
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0.16,6.2)'
    id 'org.parchmentmc.librarian.forgegradle' version '1.+'
}

apply plugin: 'org.spongepowered.mixin'

group = mod_group_id
version = minecraft_version + "-" + mod_version

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: mapping_channel, version: mapping_version

    copyIdeResources = true
    accessTransformer = file('src/main/resources/META-INF/accesstransformer.cfg')

    runs {
        configureEach {
            workingDirectory project.file("run/${it.name}")
            property 'forge.logging.markers', 'SCAN' /* REGISTRIES / REGISTRYDUMP */
            property 'forge.logging.console.level', 'debug'

            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }

        client {
            property 'forge.enabledGameTestNamespaces', mod_id
            // Support for mixins of other mods
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
        }

        clientRandom {
            parent runs.client
            // #### will be replaced with a random number | UUID is a randomly generated one
            args '--username', 'Dev####', '--uuid', 'fdb0e318-1ac3-4049-b6f8-d024c0b87a56'
        }

        server {
            property 'forge.enabledGameTestNamespaces', mod_id
            // Support for mixins of other mods
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${buildDir}/createSrgToMcp/output.srg"
        }

        data {
            args '--mod', mod_id, '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    flatDir { dirs 'dev' }
    maven { url = "https://jitpack.io" } // Mixin Squared
    maven { url = "https://www.cursemaven.com" } // CurseForge
    maven { url = "https://maven.createmod.net" } // Create
}

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    /* --- Compatibility --- */
    implementation fg.deobf("curse.maven:jade-324717:6855440") // 11.13.2

    compileOnly fg.deobf("curse.maven:fastentitytransfer-828407:5202591") // 1.3.1

    compileOnly fg.deobf("curse.maven:harvest-with-ease-602171:5968744") // 9.4.0

    // https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1&showAlphaFiles=hide
    compileOnly fg.deobf("curse.maven:sophisticated-backpacks-422301:8238726") // 3.24.53.1877
    // https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1&showAlphaFiles=hide
    compileOnly fg.deobf("curse.maven:sophisticated-storage-619320:7603098") // 1.4.55.1832
    // https://www.curseforge.com/minecraft/mc-mods/sophisticated-core/files/all?page=1&pageSize=20&gameVersionTypeId=1&showAlphaFiles=hide
    compileOnly fg.deobf("curse.maven:sophisticated-core-618298:8238725") // 1.3.50.2005

    compileOnly fg.deobf("curse.maven:toms-storage-378609:6418133") // 1.7.1

    // https://www.curseforge.com/minecraft/mc-mods/create/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1&showAlphaFiles=hide
    implementation fg.deobf("curse.maven:create-328085:7178761") // 6.0.8
    implementation(fg.deobf("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}"))

    compileOnly fg.deobf("curse.maven:wonderful-enchantments-417439:5114391") // 1.10.7
    compileOnly fg.deobf("curse.maven:majrusz-library-437409:5085683") // 7.0.5

    implementation fg.deobf("curse.maven:lets-do-farm-charm-1038103:7088013") // 1.0.14
    implementation fg.deobf("curse.maven:lets-do-vinery-704465:6965751") // 1.4.41
    implementation fg.deobf("curse.maven:lets-do-herbal-brews-951221:6458889") // 1.0.12
    implementation fg.deobf("curse.maven:do-api-864599:5468182") // 1.2.15
    implementation fg.deobf("curse.maven:architectury-api-419699:5137938") // 9.2.14

    compileOnly fg.deobf("curse.maven:quark-243121:6427817") // 4.0-462
    compileOnly fg.deobf("curse.maven:zeta-968868:7335229") // 1.0-31

    compileOnly fg.deobf("curse.maven:rightclickharvest-452834:7508764") // 4.6.1

    compileOnly fg.deobf("curse.maven:supplementaries-412082:7431873") // 3.1.42
    compileOnly fg.deobf("curse.maven:selene-499980:7541536") // 2.16.27

    compileOnly fg.deobf("curse.maven:fastworkbench-288885:5101229") // 8.0.4
    compileOnly fg.deobf("curse.maven:placebo-283644:5414631") // 8.6.2

    compileOnly fg.deobf("curse.maven:fruit-trees-355467:7372142") // 7.8.5
    compileOnly fg.deobf("curse.maven:kiwi-303657:7514218") // 11.10.01
    compileOnly fg.deobf("curse.maven:lychee-567403:7437062") // 5.1.24

    compileOnly fg.deobf("curse.maven:collectors-reap-807101:7457274") // 1.5.5
    compileOnly fg.deobf("curse.maven:blueprint-382216:6408581") // 7.1.3

    compileOnly fg.deobf("curse.maven:smarter-farmers-farmers-replant-491290:6331323") // 2.1.2
    compileOnly fg.deobf("curse.maven:selene-499980:7541536") // 2.16.27

    implementation fg.deobf("curse.maven:visual-workbench-500273:6798189") // 8.0.1
    implementation fg.deobf("curse.maven:puzzles-lib-495476:6387081") // 8.1.32

    implementation fg.deobf("curse.maven:tooltip-overhaul-1327508:7548782") // 1.4.2

    // https://www.curseforge.com/minecraft/mc-mods/kaleidoscope-cookery/files/all?page=1&pageSize=20&version=1.20.1&showAlphaFiles=hide
    implementation fg.deobf("curse.maven:kaleidoscope-cookery-1309203:8231454")

    /* --- Compatibility (Farmer's Delight addons) --- */
    // https://www.curseforge.com/minecraft/mc-mods/farmers-delight/files/all?page=1&pageSize=20&gameVersionTypeId=1&showAlphaFiles=hide
    implementation fg.deobf("curse.maven:farmers-delight-398521:8083474") // 1.3.2
    compileOnly fg.deobf("curse.maven:miners-delight-plus-689630:5038950") // 1.2.3

    compileOnly fg.deobf("curse.maven:display-delight-1144296:7176651") // 1.4.0

    /* --- Compatibility Test --- */
    implementation fg.deobf("curse.maven:croptopia-415438:4997459") // 3.0.4
    implementation fg.deobf("curse.maven:epherolib-885449:4889101") // 1.2.0

    compileOnly fg.deobf("curse.maven:crate-delight-forge-958291:5881388") // 24.11.06

    implementation fg.deobf("curse.maven:vintage-delight-949719:5847856")

    // https://www.curseforge.com/minecraft/mc-mods/corn-delight/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1&showAlphaFiles=hide
    implementation fg.deobf("curse.maven:corn-delight-577805:8219677") // 1.2.11

    // https://www.curseforge.com/minecraft/mc-mods/mysterious-mountain-lib/files/all?page=1&pageSize=20&version=1.20.1&gameVersionTypeId=1&showAlphaFiles=hide
    implementation fg.deobf("curse.maven:mysterious-mountain-lib-368098:7636232") // 1.6.34

    /* --- Test --- */
    implementation fg.deobf("curse.maven:appleskin-248787:4770828")
    implementation fg.deobf("curse.maven:jei-238222:6075247") // 15.20.0.106

    /* --- Mixin Configuration --- */
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:${mixin_extras_version}"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:${mixin_extras_version}")) {
        jarJar.ranged(it, "[${mixin_extras_version},)")
    }

    annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            mod_id           : mod_id,
            mod_name         : mod_name,
            mod_license      : mod_license,
            mod_version      : mod_version,
            mod_author       : mod_author,
            mod_description  : mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_author,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : mod_version,
                'Implementation-Vendor'   : mod_author,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}