plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.20'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

version = minecraft_version + "-" + mod_version
group = mod_group_id

repositories {
    mavenLocal()
    flatDir { dirs 'dev' }
    maven { url = "https://jitpack.io" } // Mixin Squared
    maven { url = "https://www.cursemaven.com" } // CurseForge
    maven { url = "https://maven.createmod.net" } // Create
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }

    gameTestServer {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    data {
        programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    /* --- Compatibility --- */
    implementation "curse.maven:jade-324717:7545219" // 15.10.5

//    compileOnly fg.deobf("curse.maven:fastentitytransfer-828407:5202591") // 1.3.1

    compileOnly "curse.maven:harvest-with-ease-602171:7401545" // 9.4.0
    compileOnly "curse.maven:cobweb-968456:7355650" // 1.4.0

    // https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    implementation "curse.maven:sophisticated-backpacks-422301:8238750" // 3.25.58.1880
    // https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    implementation "curse.maven:sophisticated-storage-619320:8238761" // 1.5.58.1835
    // https://www.curseforge.com/minecraft/mc-mods/sophisticated-core/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    implementation "curse.maven:sophisticated-core-618298:8238703" // 1.4.54.2004

    // https://www.curseforge.com/minecraft/mc-mods/toms-storage/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:toms-storage-378609:7917007" // 2.3.2

    // https://www.curseforge.com/minecraft/mc-mods/create/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    implementation "curse.maven:create-328085:7963363" // 6.0.10
    implementation "net.createmod.ponder:ponder-neoforge:${ponder_version}"

//    compileOnly fg.deobf("curse.maven:wonderful-enchantments-417439:5114391") // 1.10.7
//    compileOnly fg.deobf("curse.maven:majrusz-library-437409:5085683") // 7.0.5

    // https://www.curseforge.com/minecraft/mc-mods/lets-do-farm-charm/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    implementation "curse.maven:lets-do-farm-charm-1038103:7959521" // 1.1.22
    // https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    implementation "curse.maven:lets-do-vinery-704465:7539914" // 1.5.3
    // https://www.curseforge.com/minecraft/mc-mods/lets-do-herbal-brews/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    implementation "curse.maven:lets-do-herbal-brews-951221:7657017" // 1.1.3
    implementation "curse.maven:do-api-864599:5730908" // 1.3.0
    implementation "curse.maven:architectury-api-419699:5786327" // 13.0.8

    // https://www.curseforge.com/minecraft/mc-mods/quark/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:quark-243121:8146177" // 4.1-480
    // https://www.curseforge.com/minecraft/mc-mods/zeta/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:zeta-968868:7980010" // 1.1-40

    // https://www.curseforge.com/minecraft/mc-mods/rightclickharvest/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:rightclickharvest-452834:7508749" // 4.6.1
    compileOnly "curse.maven:architectury-api-419699:5786327" // 13.0.8
    compileOnly "curse.maven:jamlib-623764:6421954" // 1.3.5

    // https://www.curseforge.com/minecraft/mc-mods/supplementaries/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:supplementaries-412082:8194573" // 3.6.7
    compileOnly "curse.maven:selene-499980:7522321" // 2.29.16

    // TODO :: check if it causes issues
    compileOnly "curse.maven:fastworkbench-288885:6751534" // 9.1.3
    compileOnly "curse.maven:placebo-283644:6926281" // 9.9.1

    // Fruitful Fun 🍊
//    compileOnly fg.deobf("curse.maven:fruit-trees-355467:7372142") // 7.8.5
//    compileOnly fg.deobf("curse.maven:kiwi-303657:7514218") // 11.10.01
//    compileOnly fg.deobf("curse.maven:lychee-567403:7437062") // 5.1.24

//    implementation fg.deobf("curse.maven:collectors-reap-807101:7457274") // 1.5.5
//    implementation fg.deobf("curse.maven:blueprint-382216:6408581") // 7.1.3

    // https://www.curseforge.com/minecraft/mc-mods/smarter-farmers-farmers-replant/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:smarter-farmers-farmers-replant-491290:7120722" // 2.2.4
    compileOnly "curse.maven:selene-499980:7522321" // 2.29.16

    compileOnly "curse.maven:visual-workbench-500273:6798196" // 21.1.1
    compileOnly "curse.maven:puzzles-lib-495476:7140307" // 21.1.39

    // https://www.curseforge.com/minecraft/mc-mods/tooltip-overhaul/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:tooltip-overhaul-1327508:7907475" // 1.4.4

    implementation "curse.maven:kaleidoscope-cookery-1309203:7473813" // 1.2.0

    /* --- Compatibility (Farmer's Delight addons) --- */
    // https://www.curseforge.com/minecraft/mc-mods/farmers-delight/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    implementation "curse.maven:farmers-delight-398521:8083481" // 1.3.2

    // https://www.curseforge.com/minecraft/mc-mods/miners-delight-plus/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:miners-delight-plus-689630:8011049" // 1.4.5
    compileOnly "curse.maven:lodestone-616457:7264731" // 1.8.2

    // https://www.curseforge.com/minecraft/mc-mods/display-delight/files/all?page=1&pageSize=20&version=1.21.1&gameVersionTypeId=6&showAlphaFiles=hide
    compileOnly "curse.maven:display-delight-1144296:8188789" // 1.6.1

    /* --- Compatibility Test --- */
    implementation "curse.maven:croptopia-415438:6788725" // 4.2.1
    implementation "curse.maven:epherolib-885449:5872111" // 1.2.0

    implementation "curse.maven:crate-delight-forge-958291:7024451" // 25.09.22

//    implementation fg.deobf("curse.maven:vintage-delight-949719:5847856")

    /* --- Test --- */
    implementation "curse.maven:appleskin-248787:7517379" // 3.0.8
    runtimeOnly "curse.maven:emi-580555:6420931" // 1.1.22
    runtimeOnly "curse.maven:tmrv-1194921:7410429" // 0.7.1
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}